### ISSUE TITLE
Index out of range when opening a SVG created from svgwrite.

### ISSUE THREAD

**Issue by Houwarnick** [Amirh24/SVG-Image-Utils#1]
I get a list index out of range error when trying to open a SVG created with the svgwrite library. The created svg opens fine with firefox and intellij.
```
>>> import svgwrite
>>> from svgimgutils import SVGImgUtils
>>> dwg = svgwrite.Drawing('test.svg', profile='tiny')
>>> dwg.add(dwg.text('Test',insert = (30, 55),font_size="10px",fill='black'))
<svgwrite.text.Text object at 0x104e41f28>
>>> dwg.save()
>>> test = SVGImgUtils.fromfile('test.svg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/houstonwarnick/dev/file-service/.venv/lib/python3.6/site-packages/svgimgutils.py", line 115, in fromfile
    fig.adddata()
  File "/Users/houstonwarnick/dev/file-service/.venv/lib/python3.6/site-packages/svgimgutils.py", line 144, in adddata
    self.style_element = self.root.find('./' + self.root[0].tag + '/' + self.root[0][0].tag)
  File "src/lxml/etree.pyx", line 1167, in lxml.etree._Element.__getitem__
IndexError: list index out of range
```

**Comment by Amirh24** [comment]
svgwrite is looking for the style tag. It is usefully located as the child of the first child <defs>.
I guess that it is not included in your test.svg

**Comment by Houwarnick** [comment]
I was able to get it to work by adding the style tag inside the def tag like you mentioned. It did throw another error because it was trying to call int on the 4th letter of class name? Do all the classes have to be named `cls-1` etc.? After changing my class name to match that scheme it worked.

**Comment by Amirh24** [comment]
Yes it does. The big issue with the layering is how default ones are always named cls-x so every svg has corresponding classes so the colors mix. The utility counts the number of existing classes and adds it to the appended ones. 
I will add a limitations explanations in the wiki.
