### ISSUE TITLE
Example merge renders all layers except base black.

### ISSUE THREAD

**Issue by tb9jen** [Amirh24/SVG-Image-Utils#9]
When I run the example on my mac, I get a ton of errors that look like this: 

WARNING	Property: Unknown Property name. [1:8: fill]

It does run but the final output has all fills/strokes changed to black except for the base itself.

**Comment by kevinday** [comment]
Started playing with this today and am seeing the same warnings. Testing with some very simple svg files that I'm happy to share if it helps debug.

**Comment by Amirh24** [comment]
Hi, This library is no longer maintained. 
It's encouraged to submit PRs in order to fix any issue and improve it.

**Comment by tb9jen** [comment]
I was able to get passed it by editing in Illustrator then saving it in Inkscape to get the right metadata. Im not 100% sure what causes it but that resolved it most of the time for me.
